# Generated by Django 5.2 on 2025-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_track_file_url_track_file_alter_track_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Обложка альбома'),
        ),
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='Фото группы'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
    ]
