# Generated by Django 5.2 on 2025-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_photo_url_remove_artist_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Роль артиста'),
        ),
    ]
