# Generated by Django 5.2 on 2025-09-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_artist_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.track', verbose_name='Трек'),
        ),
    ]
