# Generated by Django 5.2 on 2025-09-06 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_rating_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('rating_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.album', verbose_name='Альбом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка альбома',
                'verbose_name_plural': 'Оценки альбомов',
                'db_table': 'оценка_альбома',
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.CreateModel(
            name='TrackRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('rating_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.track', verbose_name='Трек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка трека',
                'verbose_name_plural': 'Оценки треков',
                'db_table': 'оценка_трека',
                'unique_together': {('user', 'track')},
            },
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
