# Generated by Django 5.2 on 2025-09-06 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_albumrating_trackrating_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/', verbose_name='Фото плейлиста'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
