# Generated by Django 5.2 on 2025-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_playlisttrack_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='track_photos/', verbose_name='Фото трека'),
        ),
    ]
