# Generated by Django 5.2 on 2025-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_track_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.genre', verbose_name='Жанры'),
        ),
    ]
